const mongoose = require("mongoose");
const Complaint = require("./models/complaint-model");

const dummyData = [
  {
    date: "2024-01-09",
    time: "05:20:34",
    category: "Other",
    complaint: "Excessive noise from adjacent rooms, making it hard to study or sleep.",
    priority: "Medium",
    studentName: "Rohan Kumar",
    contact: "+919748503566",
    email: "rohan.kumar@gmail.com",
    hostel: "B3",
    floor: 3,
    roomNumber: 13,
    status: "Resolved"
  },
  {
    date: "2024-10-27",
    time: "07:34:34",
    category: "Mess and Food",
    complaint: "Hygiene standards in the mess are not maintained properly.",
    priority: "Low",
    studentName: "Aarav Gupta",
    contact: "+919135197006",
    email: "aarav.gupta@gmail.com",
    hostel: "BH3",
    floor: 5,
    roomNumber: 15,
    status: "In Progress"
  },
  {
    date: "2024-01-16",
    time: "08:15:34",
    category: "Other",
    complaint: "Excessive noise from adjacent rooms, making it hard to study or sleep.",
    priority: "High",
    studentName: "Sahil Sharma",
    contact: "+918111651327",
    email: "sahil.sharma@gmail.com",
    hostel: "BH3",
    floor: 3,
    roomNumber: 6,
    status: "Resolved"
  },
  {
    date: "2024-01-07",
    time: "22:32:34",
    category: "Other",
    complaint: "Frequent animal sightings around the hostel, which is concerning.",
    priority: "Low",
    studentName: "Karthik Gupta",
    contact: "+917967066101",
    email: "karthik.gupta@gmail.com",
    hostel: "BH2",
    floor: 4,
    roomNumber: 15,
    status: "In Progress"
  },
  {
    date: "2023-11-16",
    time: "20:25:34",
    category: "Laundry Facilities",
    complaint: "Limited washing slots, causing long waiting times.",
    priority: "High",
    studentName: "Vani Singh",
    contact: "+919075019736",
    email: "vani.singh@gmail.com",
    hostel: "B3",
    floor: 2,
    roomNumber: 9,
    status: "In Progress"
  },
  {
    date: "2023-12-25",
    time: "01:15:34",
    category: "Laundry Facilities",
    complaint: "Lack of drying racks, making it hard to dry clothes.",
    priority: "Low",
    studentName: "Ishaan Kumar",
    contact: "+918879025072",
    email: "ishaan.kumar@gmail.com",
    hostel: "BH1",
    floor: 1,
    roomNumber: 4,
    status: "Open"
  },
  {
    date: "2024-04-14",
    time: "09:14:34",
    category: "Other",
    complaint: "Excessive noise from adjacent rooms, making it hard to study or sleep.",
    priority: "High",
    studentName: "Aarav Gupta",
    contact: "+916780794196",
    email: "aarav.gupta@gmail.com",
    hostel: "BH3",
    floor: 4,
    roomNumber: 4,
    status: "In Progress"
  },
  {
    date: "2024-02-27",
    time: "17:45:34",
    category: "Washroom Facilities",
    complaint: "Washroom clogging issues, with slow drainage.",
    priority: "High",
    studentName: "Priya Singh",
    contact: "+916937010516",
    email: "priya.singh@gmail.com",
    hostel: "B3",
    floor: 5,
    roomNumber: 20,
    status: "In Progress"
  },
  {
    date: "2024-04-13",
    time: "11:14:34",
    category: "Lift/Elevator",
    complaint: "Elevator buttons are not responsive, making it difficult to operate.",
    priority: "Low",
    studentName: "Rhea Verma",
    contact: "+916881221301",
    email: "rhea.verma@gmail.com",
    hostel: "BH1",
    floor: 4,
    roomNumber: 12,
    status: "Open"
  },
  {
    date: "2023-12-12",
    time: "18:43:34",
    category: "Other",
    complaint: "Frequent animal sightings around the hostel, which is concerning.",
    priority: "Medium",
    studentName: "Neha Gupta",
    contact: "+916450352351",
    email: "neha.gupta@gmail.com",
    hostel: "BH4",
    floor: 5,
    roomNumber: 14,
    status: "Open"
  },
  {
    date: "2024-07-01",
    time: "23:45:34",
    category: "Mess and Food",
    complaint: "Utensils are often dirty and unwashed.",
    priority: "Low",
    studentName: "Ishaan Patel",
    contact: "+919418104902",
    email: "ishaan.patel@gmail.com",
    hostel: "BH4",
    floor: 2,
    roomNumber: 11,
    status: "Resolved"
  },
  {
    date: "2023-12-12",
    time: "16:19:34",
    category: "Mess and Food",
    complaint: "Utensils are often dirty and unwashed.",
    priority: "High",
    studentName: "Karthik Kumar",
    contact: "+919595063262",
    email: "karthik.kumar@gmail.com",
    hostel: "BH3",
    floor: 3,
    roomNumber: 18,
    status: "Resolved"
  },
  {
    date: "2024-05-20",
    time: "03:46:34",
    category: "Wi-Fi Issue",
    complaint: "The Wi-Fi connection is frequently down, affecting the ability to complete assignments on time.",
    priority: "Low",
    studentName: "Priya Verma",
    contact: "+918859978122",
    email: "priya.verma@gmail.com",
    hostel: "B3",
    floor: 1,
    roomNumber: 15,
    status: "In Progress"
  },
  {
    date: "2024-11-01",
    time: "12:32:34",
    category: "Wi-Fi Issue",
    complaint: "The Wi-Fi connection is frequently down, affecting the ability to complete assignments on time.",
    priority: "Medium",
    studentName: "Rohan Patel",
    contact: "+916839609017",
    email: "rohan.patel@gmail.com",
    hostel: "BH2",
    floor: 2,
    roomNumber: 1,
    status: "Resolved"
  },
  {
    date: "2024-01-13",
    time: "12:54:34",
    category: "Lift/Elevator",
    complaint: "Frequent maintenance issues cause long waiting times for the lift.",
    priority: "Low",
    studentName: "Neha Kumar",
    contact: "+917661218229",
    email: "neha.kumar@gmail.com",
    hostel: "BH2",
    floor: 5,
    roomNumber: 17,
    status: "Open"
  },
  {
    date: "2024-01-21",
    time: "12:33:34",
    category: "Mess and Food",
    complaint: "Food quality is poor, with limited healthy options.",
    priority: "Low",
    studentName: "Rhea Verma",
    contact: "+916095413195",
    email: "rhea.verma@gmail.com",
    hostel: "BH3",
    floor: 4,
    roomNumber: 20,
    status: "Open"
  },
  {
    date: "2024-05-06",
    time: "03:29:34",
    category: "Mess and Food",
    complaint: "Food quantity is inadequate during peak hours.",
    priority: "Medium",
    studentName: "Rhea Kumar",
    contact: "+918038688459",
    email: "rhea.kumar@gmail.com",
    hostel: "BH3",
    floor: 2,
    roomNumber: 7,
    status: "Open"
  },
  {
    date: "2024-07-23",
    time: "19:47:34",
    category: "Wi-Fi Issue",
    complaint: "The Wi-Fi connection is frequently down, affecting the ability to complete assignments on time.",
    priority: "Low",
    studentName: "Sahil Nair",
    contact: "+917806626823",
    email: "sahil.nair@gmail.com",
    hostel: "BH4",
    floor: 2,
    roomNumber: 18,
    status: "Resolved"
  },
  {
    date: "2024-08-30",
    time: "18:59:34",
    category: "Laundry Facilities",
    complaint: "Limited washing slots, causing long waiting times.",
    priority: "Medium",
    studentName: "Neha Gupta",
    contact: "+916269033829",
    email: "neha.gupta@gmail.com",
    hostel: "BH4",
    floor: 1,
    roomNumber: 9,
    status: "Resolved"
  },
  {
    date: "2024-08-11",
    time: "04:14:34",
    category: "Room Maintenance",
    complaint: "Fan not working properly, making the room too hot.",
    priority: "Low",
    studentName: "Lakshmi Das",
    contact: "+917129773171",
    email: "lakshmi.das@gmail.com",
    hostel: "BH2",
    floor: 3,
    roomNumber: 13,
    status: "In Progress"
  },
  {
    date: "2024-10-06",
    time: "09:37:34",
    category: "Laundry Facilities",
    complaint: "Limited washing slots, causing long waiting times.",
    priority: "Low",
    studentName: "Aarav Singh",
    contact: "+917213778110",
    email: "aarav.singh@gmail.com",
    hostel: "BH3",
    floor: 1,
    roomNumber: 10,
    status: "Open"
  },
  {
    date: "2024-03-31",
    time: "05:23:34",
    category: "Wi-Fi Issue",
    complaint: "The Wi-Fi connection is frequently down, affecting the ability to complete assignments on time.",
    priority: "Medium",
    studentName: "Neha Reddy",
    contact: "+917945699313",
    email: "neha.reddy@gmail.com",
    hostel: "BH4",
    floor: 2,
    roomNumber: 6,
    status: "Resolved"
  },
  {
    date: "2024-02-27",
    time: "17:45:34",
    category: "Lift/Elevator",
    complaint: "Frequent maintenance issues cause long waiting times for the lift.",
    priority: "Low",
    studentName: "Ishaan Mehta",
    contact: "+919507102091",
    email: "ishaan.mehta@gmail.com",
    hostel: "BH4",
    floor: 4,
    roomNumber: 6,
    status: "In Progress"
  },
  {
    date: "2023-11-30",
    time: "06:45:34",
    category: "Laundry Facilities",
    complaint: "Limited washing slots, causing long waiting times.",
    priority: "Low",
    studentName: "Rohan Gupta",
    contact: "+917352925640",
    email: "rohan.gupta@gmail.com",
    hostel: "B3",
    floor: 4,
    roomNumber: 7,
    status: "Open"
  },
  {
    date: "2024-08-28",
    time: "07:33:34",
    category: "Other",
    complaint: "Excessive noise from adjacent rooms, making it hard to study or sleep.",
    priority: "Low",
    studentName: "Lakshmi Gupta",
    contact: "+918714976123",
    email: "lakshmi.gupta@gmail.com",
    hostel: "BH3",
    floor: 2,
    roomNumber: 16,
    status: "Resolved"
  },
  {
    date: "2024-03-24",
    time: "06:43:34",
    category: "Washroom Facilities",
    complaint: "Issues with water availability in the shower.",
    priority: "Low",
    studentName: "Neha Das",
    contact: "+919668038631",
    email: "neha.das@gmail.com",
    hostel: "BH3",
    floor: 2,
    roomNumber: 9,
    status: "Resolved"
  },
  {
    date: "2024-04-06",
    time: "09:33:34",
    category: "Mess and Food",
    complaint: "Utensils are often dirty and unwashed.",
    priority: "Low",
    studentName: "Lakshmi Mehta",
    contact: "+917075599515",
    email: "lakshmi.mehta@gmail.com",
    hostel: "BH2",
    floor: 5,
    roomNumber: 9,
    status: "In Progress"
  },
  {
    date: "2024-03-17",
    time: "11:56:34",
    category: "Lift/Elevator",
    complaint: "Lift often gets stuck between floors.",
    priority: "High",
    studentName: "Priya Gupta",
    contact: "+916141313058",
    email: "priya.gupta@gmail.com",
    hostel: "BH4",
    floor: 3,
    roomNumber: 20,
    status: "Open"
  },
  {
    date: "2024-03-21",
    time: "02:29:34",
    category: "Other",
    complaint: "Excessive noise from adjacent rooms, making it hard to study or sleep.",
    priority: "High",
    studentName: "Priya Verma",
    contact: "+916144522855",
    email: "priya.verma@gmail.com",
    hostel: "BH1",
    floor: 2,
    roomNumber: 5,
    status: "Resolved"
  },
  {
    date: "2024-09-23",
    time: "08:22:34",
    category: "Mess and Food",
    complaint: "Hygiene standards in the mess are not maintained properly.",
    priority: "Medium",
    studentName: "Rhea Gupta",
    contact: "+916750621275",
    email: "rhea.gupta@gmail.com",
    hostel: "BH1",
    floor: 3,
    roomNumber: 14,
    status: "Open"
  },
  {
    date: "2024-01-30",
    time: "06:01:34",
    category: "Laundry Facilities",
    complaint: "Limited washing slots, causing long waiting times.",
    priority: "High",
    studentName: "Lakshmi Nair",
    contact: "+917838002107",
    email: "lakshmi.nair@gmail.com",
    hostel: "BH3",
    floor: 5,
    roomNumber: 10,
    status: "In Progress"
  },
  {
    date: "2024-07-15",
    time: "16:29:34",
    category: "Wi-Fi Issue",
    complaint: "The Wi-Fi connection is frequently down, affecting the ability to complete assignments on time.",
    priority: "Medium",
    studentName: "Karthik Nair",
    contact: "+918593126321",
    email: "karthik.nair@gmail.com",
    hostel: "BH2",
    floor: 2,
    roomNumber: 13,
    status: "Open"
  },
  {
    date: "2024-11-06",
    time: "21:00:34",
    category: "Laundry Facilities",
    complaint: "Lack of drying racks, making it hard to dry clothes.",
    priority: "Low",
    studentName: "Vani Reddy",
    contact: "+919922392990",
    email: "vani.reddy@gmail.com",
    hostel: "BH4",
    floor: 1,
    roomNumber: 19,
    status: "In Progress"
  },
  {
    date: "2024-07-06",
    time: "04:59:34",
    category: "Washroom Facilities",
    complaint: "Washroom clogging issues, with slow drainage.",
    priority: "Medium",
    studentName: "Rohan Verma",
    contact: "+918292446873",
    email: "rohan.verma@gmail.com",
    hostel: "B3",
    floor: 1,
    roomNumber: 15,
    status: "In Progress"
  },
  {
    date: "2024-01-28",
    time: "13:31:34",
    category: "Other",
    complaint: "Frequent animal sightings around the hostel, which is concerning.",
    priority: "High",
    studentName: "Vani Reddy",
    contact: "+918244136477",
    email: "vani.reddy@gmail.com",
    hostel: "BH4",
    floor: 4,
    roomNumber: 12,
    status: "In Progress"
  },
  {
    date: "2024-07-12",
    time: "05:02:34",
    category: "Laundry Facilities",
    complaint: "Washing machines are often broken or out of service.",
    priority: "Medium",
    studentName: "Aarav Singh",
    contact: "+919938593520",
    email: "aarav.singh@gmail.com",
    hostel: "BH1",
    floor: 5,
    roomNumber: 18,
    status: "Resolved"
  },
  {
    date: "2024-10-20",
    time: "00:35:34",
    category: "Room Maintenance",
    complaint: "Missing essential items like switches and plug points.",
    priority: "Medium",
    studentName: "Sushant",
    contact: "+918244136477",
    email: "vani.reddy@gmail.com",
    hostel: "BH4",
    floor: 2,
    roomNumber: 102,
    status: "In Progress"
  }

];

const insertData = async () => {
  try {
    await mongoose.connect("mongodb+srv://nottpande:pussy69@aditya.h8qrh.mongodb.net/?retryWrites=true&w=majority&appName=Aditya", {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });

    await Complaint.insertMany(dummyData);
    console.log("Dummy data inserted successfully!");
  } catch (err) {
    console.error("Error inserting dummy data:", err);
  } finally {
    mongoose.connection.close();
  }
};

insertData();